### PR TITLE
Math Magicians: setup

### PR DESCRIPTION
**Pull request by ragangithub**
- Set up a React app.

### CODE REVIEW

**Comment by ragangithub** [comment]
- Fixed linter error

**Review by wayungi — COMMENTED** [review]
Hi @ragangithub , 
image

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌ ❌ 

- [ ] You have submitted a project that has an unprofessional readme

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by ragangithub** [comment]
- Update README file

**Review by wayungi — COMMENTED** [review]
Hi @ragangithub , 
image

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌ ❌ 

- [ ] You have submitted a project with an unprofessional readme
    - Please fill in the future features 👍🏾 
    - Delete the live demo section since the project is not deployed 💯 
    - Add brief summary of what you have done in the PR description. You can get this  information from the project requirements since these requirements are what you have done 😄 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by wayungi** [comment]
hello @ragangithub , please do not write PR summaries like **Fixed linter error**. Always write a brief summary that includes the project requirements rewarded as tasks you have done. forexample

-  Create react application using CRA command
- Delete all starter files
- Add index.js file ....
- ....

**Comment by ragangithub** [comment]
- created React app using CRA
- updated README file
- fixed linter errors

**Review by TedLivist — APPROVED** [review]
## STATUS: APPROVED ✔️ ✔️

Hi @ragangithub,

✔️ Good documentation

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
